### ISSUE TITLE
Error: Exception on /webhook

### ISSUE THREAD

**Issue by krakatoa23** [jg-fisher/python-telegram-bot#3]
Getting this error, don't know how to solve it:

.\app.py returns:

* Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

127.0.0.1 - - [04/Aug/2020 12:21:43] "←[35m←[1mPOST /webhook HTTP/1.1←[0m" 500 -
[2020-08-04 12:21:43,576] ERROR in app: Exception on /webhook [POST]

Traceback (most recent call last):

  File "C:\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File ".\app.py", line 13, in index
    bot.parse_webhook_data(req)
  File "C:\Users\~\telegram-bot\telegram_bot.py", line 37, in parse_webhook_data
    self.last_name = message['from']['last_name']
KeyError: 'last_name'

**Comment by krakatoa23** [comment]
Apparently the code wasn't detecting the last name attribute. I just transformed  the parts where "last_name" was mentioned into comments with # and it worked!
